### ISSUE TITLE
feat(image): avoid under image

### ISSUE THREAD

**Issue by rbalet** [werthdavid/ngx-kjua#94]
## Description
Would it be doable to avoid rendering the middle of the qr-code ? 

This would enable having gradient under the qr-code

<img width="103" alt="image" src="https://github.com/werthdavid/ngx-kjua/assets/44493964/843f06eb-46bd-4476-b003-b7ddd54cde8d">

**Comment by werthdavid** [comment]
I have an idea... will see when I can find time

**Comment by rbalet** [comment]
@werthdavid nice! You can always let me know how you'd implement that and I can try on my own

**Comment by werthdavid** [comment]
So the idea is to use a globalCompositeOperation of "destination-out" with a dummy image.
See here: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation?retiredLocale=de#changing_the_composite_operation
With this, you could remove the middle part. Should be quite easy. 
BUT as always there's a catch.
It needs to be done inside kjua-svg. Which is not a problem generally speaking. I just thought that I could move all the code from kjua-svg directly to ngx-kjua which would also help avoiding those "optimization bailout" messages. 
What do you say?

**Comment by werthdavid** [comment]
yeah well, actually we don't even need ts-kjua-svg IMHO. If there is a proper build process, a JS library can be used without hassle, typescript definitions are there already. If you like, you are more than welcome to create a PR on kjua-svg (I'm the owner there as well).

**Comment by rbalet** [comment]
@werthdavid Nice, I wasn't aware of it.

But that said, i'm not sure I understand why you wanted to import the kjua-svg code in ngx-kjua then, if you're able to fix the error at the source.

Can you create the required issue on the kjua-svg library and assign it to me ?  (Or mention me in the issue).

I'll have a look this afternoone.

That said, I may need more time that you for the solution you've proposed with compositionOperation, as I'm actually specialised in Angular, but not the rest '^^ (But always eager to learn)

**Comment by werthdavid** [comment]
I wanted to import the code because it would be the quicker (but dirty) solution. I forked kjua-svg from the original "kjua" only to have svg support but the whole project for me was only there to have the angular component. the original "kjua" now has svg support as well btw. 

so the clean way would be to fix kjua-svg, no doubt.

If you want to implement the feature, I'd do the following:
- create a new option
- listen for the option here: https://github.com/werthdavid/kjua/blob/76868583823b535fd1cba042932750f31a82f159/src/lib/create_canvas_qrcode.js#L61 and here https://github.com/werthdavid/kjua/blob/76868583823b535fd1cba042932750f31a82f159/src/lib/create_svg_qrcode.js#L240
- use "destination-out" in that case

**Comment by rbalet** [comment]
@werthdavid Ah I see, so, the must would be to use `kjua` directly, instead of `kjua-svg` and as we cannot edit `kjua` and it seems to not being maintained anymore, it could be worth to import it into the `ngx-kjua` project directly.

So I'll implement it directly in `ngx-kjua`.

Then, if we wish to migrate it to the official `kjua` library, we could, and ask them to merge it.
But that we we could move forward with the `ngx-kjua` does that makes sense ? (Sorry just wanna be sure '^^)

**Comment by werthdavid** [comment]
Careful! The original kjua (which is lrsjng/kjua) is not maintained anymore. My fork (werthdavid/kjua) is published as "kjua-svg" as I added svg support (later, lrsjng added svg support to the original  lrsjng/kjua as well). I didn't switch back to the original kjua and kept my fork as I added the "Image as Code" option there. The logic of this option can be "safely inherited" (as I call "copy&paste") to implement this feature.

So if I would do it, I would potentially: 
- copy the code from kjua-svg (werthdavid/kjua) to this repo
- make the changes as stated in the answer above
(to make the changes, it is NOT actually necessary to copy the sources to THIS repo! But since the original kjua and kjua-svg have a strage build process we get optimization-warnings from angular when it is used here. which has always been going on my nerves... so at this point when I would touch kjua-svg again I would copy the sources here as we have a proper build process here) hope my intention gets clear!

OR:
- make the changes in werthdavid/kjua, bump the version, use the version here and we're good to go.
(but then there would still be the optimization-warnings. but they are totally unrelated to this issue!)

does that make sense?

**Comment by rbalet** [comment]
@werthdavid Yeh, that warning also did get on my nerves.

I think I've understood everything, I'll start right away, thx for the clarification

**Comment by rbalet** [comment]
@werthdavid I've done `.ts` implementation, we're just missing this part, which I'll do (or you can do preferably), once this one have already been accepted 

## ToDo
* [ ] create a new option
* [ ] Listen for the option here: https://github.com/werthdavid/kjua/blob/76868583823b535fd1cba042932750f31a82f159/src/lib/create_canvas_qrcode.js#L61 and here https://github.com/werthdavid/kjua/blob/76868583823b535fd1cba042932750f31a82f159/src/lib/create_svg_qrcode.js#L240
* [ ] use "destination-out" in that case

**Comment by werthdavid** [comment]
thank you @rbalet ! I will take a look!

**Comment by werthdavid** [comment]
So the PoC works, but unfortunately only for canvas and img, my idea with "globalCompositeOperation" doesn't work with svg... is that a limitation you could live with?

**Comment by rbalet** [comment]
@werthdavid I'd say it is already better than nothing 😍.

If you wish, I could add an implementation that throw an error when svf and glovalCompositieOperstion are used.

And thx for the implementation, really appreciated

**Comment by werthdavid** [comment]
I will merge the canvas/image option now and throw an error for svg. no big deal. I have an idea how it COULD work with svg but don't really have time these days.

**Comment by werthdavid** [comment]
sorry for the delay, had some issues with the unit-test, the option is now available. please let me know if everything works with 18.1.0

**Comment by rbalet** [comment]
@werthdavid No problem, thx a lot for doing it either way.

I do get the following error
![image](https://github.com/werthdavid/ngx-kjua/assets/44493964/e2f96a38-93f2-43c5-a20b-43e0e1fde6bb)

That I've fixed right away in that [pull request](https://github.com/werthdavid/ngx-kjua/compare/master...rbalet:ngx-kjua:patch-1)

**Comment by rbalet** [comment]
@werthdavid Can you show me where to add the 

Also, somehow we now get this error while importing (Funnily enough, this does work inside the `ngx-kjua` test library..  
Maybe you have an Idea

![image](https://github.com/werthdavid/ngx-kjua/assets/44493964/3d09e5c1-f3b5-4a98-ac4f-535461ee62d4)

**Comment by werthdavid** [comment]
add the what? 🙈 
how can I reproduce this error?

**Comment by rbalet** [comment]
@werthdavid so 

## Step to reproduce
in the kjua project
1. run `npm i ngx-kjua@latest`
2. use the `ngxKjuaComponent` > `import { NgxKjuaComponent } from "ngx-kjua";`
3. You'll have the error. 

Somehow it seems like it is wrongly complied

I have seen the following discussion : https://stackoverflow.com/questions/43946738/webpack-compile-error-typeerror-webpack-imported-module-1-is-not-a-funct

It seems it could be due to the import

I may think that this can be the problem.
<img width="656" alt="image" src="https://github.com/werthdavid/ngx-kjua/assets/44493964/6798e744-8a36-491d-8cbf-d15c5c832f07">

But I don't know how to import this one in a other manner..

**Comment by rbalet** [comment]
@werthdavid Hey, I've tested the following fix. https://github.com/werthdavid/ngx-kjua/pull/99

I've let the `preserveSymlink` in the `angular.json` file so that you can try with the `npm link`.

For me, it seems to have fixed the issue.

Can you please try out ?

**Comment by Sergiobop** [comment]
Hi @rbalet , is this the same issue i described here? #98 

You talk about the same stringToBytes line

Thanks

**Comment by rbalet** [comment]
@Sergiobop Exactly

**Comment by rbalet** [comment]
@werthdavid I confirm that this is working.

That said, this does not resolve this issue as the image is in the qr-code, and not cut out of it

(But still looks great )
![image](https://github.com/werthdavid/ngx-kjua/assets/44493964/ca6c4e99-7b3e-45e8-83a6-0ae2700fd4f5)

**Comment by werthdavid** [comment]
What settings did you provide for given code?

**Comment by rbalet** [comment]
@werthdavid Forget what I've said.

Closing the issue as it works juste like it  should.
Thx again for your work
